### ISSUE TITLE
The stroke path is wired when at corner.

### ISSUE THREAD

**Issue by KittenYang** [ole/CGPathHitTesting#2]
<img width="300" alt="2016-10-10 5 46 29" src="https://cloud.githubusercontent.com/assets/5517281/19232363/e21a39fa-8f11-11e6-9366-0bd9dbe85b43.png">

As you can see, at the four corners of the rect, there appear wired broken lines. Is the bug of Core Graphics?Any suggestion will helpful.Thanks.

**Comment by ole** [comment]
Can you please post the relevant code so that I can try it out? Thanks.

**Comment by KittenYang** [comment]
Just make `selectionRect` visible: add those two line code:
```
                [[UIColor blackColor] setStroke];
                [selectionRect stroke];
```

to `DrawingView.m` at line 55 - line 56.You will see that.

**Comment by KittenYang** [comment]
In fact, I didn't do anything,just run you code and add a random shape,then select it.The dash lines showed in the picture,and you can see those wired broken line.You can run your project to check it.
<img width="590" alt="2016-10-12 11 05 41" src="https://cloud.githubusercontent.com/assets/5517281/19296187/59389562-906c-11e6-9097-232f91e48d29.png">

**Comment by ole** [comment]
Ah, I see, sorry. I never noticed this problem before.

And I can't explain it, either. I played around a little bit with different arguments for `CGPathCreateCopyByStrokingPath` (`miterLimit`, `lineJoin`) in [DrawingView.m:46](https://github.com/ole/CGPathHitTesting/blob/master/PathHitTesting/DrawingView.m#L46), which is where the selection outline is created and drawn, but nothing seemed to have any effect. I don't know why the path is shaped in this way, sorry.

**Comment by KittenYang** [comment]
Umm... maybe it's a bug of CoreGraphic.
